"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0.2/ref/settings/
"""

from config import db

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sv3bn4w^rir+zz4@jh_cse38bi3sxh#3s-3ro@yybzrmk98=bp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

SHARED_APPS = [
    "django_tenants",                 # debe ir primero
    "django.contrib.contenttypes",    # requerido por tenants
    "django.contrib.staticfiles",
    "widget_tweaks",
    "django_user_agents",
    "core",                           # aquí van Cliente (Tenant) y Dominio
]

# apps por-tenant (viven dentro de cada schema)
TENANT_APPS = [
    "django.contrib.auth",
    "django.contrib.admin",
    "django.contrib.sessions",
    "django.contrib.messages",

    # tus apps de negocio por-tenant
    "security",
    "user",        # tu AUTH_USER_MODEL
    "login",       # si este módulo muestra login dentro del subdominio del tenant
    "dashboard",
    "pos",
    "reports",
]

INSTALLED_APPS = SHARED_APPS + [a for a in TENANT_APPS if a not in SHARED_APPS]

DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)
PUBLIC_SCHEMA_NAME = "public"
TENANT_NOT_FOUND_EXCEPTION = False
TENANT_MODEL = "core.Cliente"
TENANT_DOMAIN_MODEL = "core.Dominio"

ROOT_URLCONF = "core.urls_tenants"        # para subdominios (tenants)
PUBLIC_SCHEMA_URLCONF = "core.urls_public"  # para dominio raíz (public)

AUTH_USER_MODEL = "user.User"

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

MAIN_DOMAIN = os.getenv("MAIN_DOMAIN", "localhost")


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'security.functions.system_information',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0.2/ref/settings/#databases

DATABASES = db.POSTGRESQL

# Password validation
# https://docs.djangoproject.com/en/4.0.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')

MEDIA_URL = '/media/'

# Login

LOGIN_REDIRECT_URL = '/dashboard/'

LOGOUT_REDIRECT_URL = '/login/'

LOGIN_URL = '/login/'


# Email

EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.in-planet.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'wdavila@in-planet.net'
EMAIL_HOST_PASSWORD = 'Apolo@2219'
EMAIL_BACKEND = 'core.libs.smtp.EmailBackend'

# Configurations

LOCALHOST = 'algorisoft.com'

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

SESSION_COOKIE_NAME = 'factora'

GROUPS = {
    'client': 2,
}

SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# Default primary key field type
# https://docs.djangoproject.com/en/4.0.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
